import type { Metadata } from 'next';
import { suit } from '@/styles/typography';
import './globals.css';
import { Header, HeaderNav } from './common/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={suit.className}>
        <Header showNav={true} />
        <div>{children}</div>
      </body>
    </html>
  );
}
